### ISSUE TITLE
Direct Private Messages

### ISSUE THREAD

**Issue by pichumy** [pichumy/Mediacord#5]
- [ ] Users should be able to send messages directly to other users
- [ ] Adequate Styling
- [ ] Smooth bug-free navigation
- [ ] Seeded

**Comment by eshoule** [comment]
- [ ] When I register, the user icon does not show up in the bottom left - empty photo icon is displaying
- [ ] When I create a new channel and click submit, the modal does not close.
- [ ] When I click on find or start a conversation, it appears I can only search for another user - not a channel conversation name. Allow a user to search channels, DMs, and users. 
- [ ] When I search to invite someone to a direct message it does not appear to let me select a member from the search - it only selects the first one.
- [ ] Not everyone's icons show up on the messages users index until I refresh the page.
- [ ] Add notifications to let the user know they have direct messages pending- otherwise there is no way I would know.
- [ ] When I am invited to a direct message - the direct message name appears as my username like I am having a conversation with myself instead of the other message member's names.
- [ ] Improve styling to make it look cleaner and closer to the real website.
- [ ] Seed more data - users, messages, etc.

In general, there appear to be several bugs, so you should work on making navigation around the site smoother, and improving styling.
